/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it252.dataEnter;

import java.io.File;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author nicolas
 */
public class dataEnter extends javax.swing.JFrame {
    ArrayList stars = new ArrayList();
    
    /**
     * Creates new form dataEnter
     */
    public dataEnter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        districtSelect = new javax.swing.ButtonGroup();
        repIDLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        totalSuppliesLabel = new javax.swing.JLabel();
        totalBooksLabel = new javax.swing.JLabel();
        totalPaperLabel = new javax.swing.JLabel();
        totalSalesLabel = new javax.swing.JLabel();
        districtLabel = new javax.swing.JLabel();
        contact = new javax.swing.JComboBox();
        enterID = new javax.swing.JTextField();
        enterFirst = new javax.swing.JTextField();
        enterLast = new javax.swing.JTextField();
        enterSupplies = new javax.swing.JTextField();
        enterBooks = new javax.swing.JTextField();
        enterPaper = new javax.swing.JTextField();
        totals = new javax.swing.JTextField();
        enterContact = new javax.swing.JTextField();
        north = new javax.swing.JRadioButton();
        south = new javax.swing.JRadioButton();
        east = new javax.swing.JRadioButton();
        west = new javax.swing.JRadioButton();
        quitButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        enterButton = new javax.swing.JButton();
        displayLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterDisplay = new javax.swing.JTextArea();
        logButton = new javax.swing.JButton();
        deleteFileButton = new javax.swing.JButton();
        evalButton = new javax.swing.JButton();
        starsButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        repIDLabel.setText("Rep ID:");

        firstNameLabel.setText("First Name:");

        lastNameLabel.setText("Last Name:");

        totalSuppliesLabel.setText("Total Supplies:");

        totalBooksLabel.setText("Total Books:");

        totalPaperLabel.setText("Total Paper:");

        totalSalesLabel.setText("Total Sales:");

        districtLabel.setText("District:");

        contact.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Email", "Phone", "Visit Address" }));
        contact.setToolTipText("");
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });

        enterID.setText("id");
        enterID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enterIDFocusGained(evt);
            }
        });

        enterFirst.setText("first");

        enterLast.setText("last");

        enterSupplies.setText("0");
        enterSupplies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterSuppliesActionPerformed(evt);
            }
        });

        enterBooks.setText("0");

        enterPaper.setText("0");

        enterContact.setText("contact");

        districtSelect.add(north);
        north.setText("North");
        north.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                northActionPerformed(evt);
            }
        });

        districtSelect.add(south);
        south.setText("South");

        districtSelect.add(east);
        east.setText("East");

        districtSelect.add(west);
        west.setText("West");

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        enterButton.setText("Enter");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        displayLabel.setText("Display:");

        enterDisplay.setColumns(20);
        enterDisplay.setRows(5);
        jScrollPane1.setViewportView(enterDisplay);

        logButton.setText("Display Reps");
        logButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButtonActionPerformed(evt);
            }
        });

        deleteFileButton.setText("Delete File");
        deleteFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFileButtonActionPerformed(evt);
            }
        });

        evalButton.setText("Evaluate");
        evalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evalButtonActionPerformed(evt);
            }
        });

        starsButton.setText("Display Stars");
        starsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starsButtonActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteFileButton)
                    .addComponent(logButton)
                    .addComponent(evalButton)
                    .addComponent(starsButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enterButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(north)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(south)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(east)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(west))
                                .addComponent(totals, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(enterContact, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(enterPaper, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(enterBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(enterSupplies, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(enterLast, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(enterFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(enterID, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quitButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(contact, javax.swing.GroupLayout.Alignment.TRAILING, 0, 1, Short.MAX_VALUE)
                        .addComponent(repIDLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(firstNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lastNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalSuppliesLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalBooksLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalPaperLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalSalesLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(districtLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(509, 509, 509))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {districtLabel, firstNameLabel, lastNameLabel, repIDLabel, totalBooksLabel, totalPaperLabel, totalSalesLabel, totalSuppliesLabel});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deleteFileButton, evalButton, logButton, starsButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(repIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(enterID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(quitButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enterFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enterLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalSuppliesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enterSupplies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalBooksLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enterBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPaperLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enterPaper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalSalesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(districtLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(north)
                    .addComponent(south)
                    .addComponent(east)
                    .addComponent(west))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contact)
                            .addComponent(enterContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enterButton)
                            .addComponent(clearButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(displayLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(starsButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(evalButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteFileButton)
                                .addGap(12, 12, 12))
                            .addComponent(jScrollPane1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(196, 196, 196))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {deleteFileButton, evalButton, logButton, starsButton});

        pack();
    }// </editor-fold>                        

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void northActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        //quit
        System.exit(0);
    }                                          

    public class DocumentEventDemo {
        Object textField = totals;
        
    }
    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
       // First define variables.
        String repID, firstName, lastName, contact;
        String district = "Not Selected";
        float supplies, paper, books, total;
        //set variables
        repID = enterID.getText();
        firstName = enterFirst.getText();
        lastName = enterLast.getText();
        supplies = Float.parseFloat(enterSupplies.getText());
        paper = Float.parseFloat(enterPaper.getText());
        books = Float.parseFloat(enterBooks.getText());
        if (north.isSelected()) {
            district = "NORTH";
        }
        if (south.isSelected()) {
            district = "SOUTH";
        }
        if (east.isSelected()) {
            district = "EAST";
        }
        if (west.isSelected()) {
            district = "WEST";
        }
        //add and display
        total = supplies+paper+books;
        totals.setText(String.valueOf(total));
        contact = enterContact.getText();
        
        WriteTo logData = new WriteTo();
    
        logData.store("salesrep.txt", repID + ',' + firstName  + "," + lastName  + "," + 
                String.valueOf(books) + "," + String.valueOf(paper) + "," +
                String.valueOf(supplies) + "," + String.valueOf(total) + "," + 
                district + "," + contact, true);
        
        enterDisplay.append("Data saved." + System.lineSeparator());
        
        
        
       
    }                                           

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        //reset text area
        enterID.setText("");
        enterFirst.setText("");
        enterLast.setText("");
        enterSupplies.setText("0");
        enterPaper.setText("0");
        enterBooks.setText("0");
        totals.setText("");
        enterContact.setText("");
        enterDisplay.setText("");
        districtSelect.clearSelection();
    }                                           

    private void enterSuppliesActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
        ReadFrom myReader = new ReadFrom();
        String[][] fileContents = {};
        fileContents = myReader.read("salesrep.txt");
        int y = 0;
        enterDisplay.append("~~~ Loading ~~~" + System.lineSeparator());
        for (int x = 0 ; x < 100 ; x++){
            if (fileContents[x][y] == null){
                enterDisplay.append("done.");
                enterDisplay.append(System.lineSeparator());
                break;
            }else{
                enterDisplay.append("ID: " +fileContents[x][y] + ", Name: " + 
                    fileContents[x][y+1]  + " " + fileContents[x][y+2]  + ", Books: $" + 
                fileContents[x][y+3] + ", Paper: $" + fileContents[x][y+4] +
                    ", Supplies: $" + fileContents[x][y+5] + ", Total: $" + 
                        fileContents[x][y+6] + ", District: " + fileContents[x][y+7] +
                        ", Contact: " + fileContents[x][y+8]);
                enterDisplay.append(System.lineSeparator());
            }
            
        }
        
    }                                         

    private void deleteFileButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        WriteTo logData = new WriteTo();
        
        int check = JOptionPane.showConfirmDialog(this, "This action will delete you file. \n Are you sure?");
        
        String file = JOptionPane.showInputDialog("Which file would you like to delete?");
        
        if (check == 0){
            logData.store(file, null, false);
        }
        
    }                                                

    private void enterIDFocusGained(java.awt.event.FocusEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void evalButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        
        String repID, firstName, lastName, contact;
        String district = "Not Selected";
        float supplies, paper, books, total;
        //set variables
        repID = enterID.getText();
        firstName = enterFirst.getText();
        lastName = enterLast.getText();
        supplies = Float.parseFloat(enterSupplies.getText());
        paper = Float.parseFloat(enterPaper.getText());
        books = Float.parseFloat(enterBooks.getText());
        if (north.isSelected()) {
            district = "NORTH";
        }
        if (south.isSelected()) {
            district = "SOUTH";
        }
        if (east.isSelected()) {
            district = "EAST";
        }
        if (west.isSelected()) {
            district = "WEST";
        }
        //add and display
        total = supplies+paper+books;
        totals.setText(String.valueOf(total));
        contact = enterContact.getText();
        
        WriteTo logData = new WriteTo();
        
        
        if (total >= 8000){
            enterDisplay.append("Congratulations, you're a Star!" + System.lineSeparator());
          
        logData.store("stars.txt", repID + ',' + firstName  + "," + lastName  + "," + 
                String.valueOf(books) + "," + String.valueOf(paper) + "," +
                String.valueOf(supplies) + "," + String.valueOf(total) + "," + 
                district + "," + contact, true);
        
        }
        else{
            enterDisplay.append("Sorry, you need $8,000 or more in sales to be a star."
            + System.lineSeparator());
        }
        
        
    }                                          

    private void starsButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        
        
        ReadFrom myReader = new ReadFrom();
        String[][] fileContents = {};
        fileContents = myReader.read("stars.txt");
        int y = 0;
        enterDisplay.append("~~~ Loading Stars ~~~" + System.lineSeparator());
        for (int x = 0 ; x < 100 ; x++){
            if (fileContents[x][y] == null){
                enterDisplay.append("done.");
                enterDisplay.append(System.lineSeparator());
                break;
            }else{
                /*
                enterDisplay.append("ID: " +fileContents[x][y] + ", Name: " + 
                    fileContents[x][y+1]  + " " + fileContents[x][y+2]  + ", Books: $" + 
                fileContents[x][y+3] + ", Paper: $" + fileContents[x][y+4] +
                    ", Supplies: $" + fileContents[x][y+5] + ", Total: $" + 
                        fileContents[x][y+6] + ", District: " + fileContents[x][y+7] +
                        ", Contact: " + fileContents[x][y+8]);
                enterDisplay.append(System.lineSeparator());
                */
                //create instance of SalesRep with constructors
                SalesRep newRep = new SalesRep(fileContents[x][y], 
                        fileContents[x][y+1],
                        fileContents[x][y+2], 
                        Float.parseFloat(fileContents[x][y+3]), 
                        Float.parseFloat(fileContents[x][y+4]), 
                        Float.parseFloat(fileContents[x][y+5]), 
                        Float.parseFloat(fileContents[x][y+6]), 
                        fileContents[x][y+7], 
                        fileContents[x][y+8]);
                //add the new salesRep object to the global arraylist
                stars.add(newRep);
                
                //user overridden tostring to append text area
                enterDisplay.append(stars.get(x).toString());
                enterDisplay.append(System.lineSeparator());
            }
            
        }
        
        //System.out.println(stars.toString());
        
    }                                           

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        File myFile = new File("/Users/nicolas/Desktop/IT252/salesrep.txt");
        Scanner scan = new Scanner("/Users/nicolas/Desktop/IT252/salesrep.txt");
        enterDisplay.append(scan.nextLine());
        enterDisplay.append(System.lineSeparator());
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataEnter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataEnter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataEnter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataEnter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataEnter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton clearButton;
    private javax.swing.JComboBox contact;
    private javax.swing.JButton deleteFileButton;
    private javax.swing.JLabel displayLabel;
    private javax.swing.JLabel districtLabel;
    private javax.swing.ButtonGroup districtSelect;
    private javax.swing.JRadioButton east;
    private javax.swing.JTextField enterBooks;
    private javax.swing.JButton enterButton;
    private javax.swing.JTextField enterContact;
    private javax.swing.JTextArea enterDisplay;
    private javax.swing.JTextField enterFirst;
    private javax.swing.JTextField enterID;
    private javax.swing.JTextField enterLast;
    private javax.swing.JTextField enterPaper;
    private javax.swing.JTextField enterSupplies;
    private javax.swing.JButton evalButton;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JButton logButton;
    private javax.swing.JRadioButton north;
    private javax.swing.JButton quitButton;
    private javax.swing.JLabel repIDLabel;
    private javax.swing.JRadioButton south;
    private javax.swing.JButton starsButton;
    private javax.swing.JLabel totalBooksLabel;
    private javax.swing.JLabel totalPaperLabel;
    private javax.swing.JLabel totalSalesLabel;
    private javax.swing.JLabel totalSuppliesLabel;
    private javax.swing.JTextField totals;
    private javax.swing.JRadioButton west;
    // End of variables declaration                   
}
